### ISSUE TITLE
폴더링 리팩토링 제의

### ISSUE THREAD

**Issue by iamjooon2** [CMC-Hackathon-Team1/Server-V2#44]
## :loudspeaker: 이슈 내용
> 언더바로 시작하는 _config, _entities, _middlewares, _utilities를 리팩토링 하는 것은 어떠세요?
## :page_with_curl: 상세 내용
- 네스트가 컴공선배 노드 템플릿처럼 feature별로 폴더링을 하다보니, 이거에 맞춰서 common이라는 디렉토리를 만들고 위 디렉토리들을 정리하는 것은 어떨까요?
- 네스트의 interceptor나, decorator 같은 것들도 여기다가 넣을 수 있어서 확장성 면에서도 나쁘지 않다고 생각합니다
- 보기 편하시려고(맨 위에 올라오게 하려고) 언더바 붙이신 것 같아서, 많이 사용하는 폴더링 패턴이 효율적일 것 같아 이슈로 올려봅니다!
- 이런 방법도 있어요! 라고 생각해주시면 감사하겠습니다ㅠ
  + config는 성격이 조금 다르니, src랑 같은 경로에 두는 방법도 괜찮을 것 같아요!
## :round_pushpin: 참고 내용
- [사용 예 1](https://github.com/andrechristikan/ack-nestjs-boilerplate-kafka/tree/main/src)
- [사용 예 2](https://github.com/chnirt/nestjs-restful-best-practice/tree/master/src)

**Comment by HBSPS** [comment]
넵 저는 좋다고 생각합니다. 처음 엔티티 폴더 만들 때 말씀하신대로 디렉토리 상단에 위치하도록 하기 위해서 언더바를 붙였습니다. 같은 목적이니 폴더링 패턴을 따르는게 더 좋을 것 같네요😀

**Comment by bjho606** [comment]
저도 좋은데 그럼 어떻게 나누는게 좋을까요??

**Comment by iamjooon2** [comment]
@bjho606 @HBSPS
config는 src와 같은 경로에 두고
entity, util, middleware는 언더바 빼고 src/common을 만든 다음 안에 넣어버릴까요?
[ 이런 느낌입니다 ](https://github.com/CMC-Hackathon-Team1/Server-V2/tree/refactor/common)

@J-MU 민욱님 의견도 궁금합니당

**Comment by J-MU** [comment]
늦게 확인해서 죄송해요 이제 봤네요
저고 좋은거 같아요

**Comment by bjho606** [comment]
아하 좋습니다!

**Comment by iamjooon2** [comment]
적용해서 dev 브랜치 머지했습니다~
