### ISSUE TITLE
EC2에서 Nest Build가 안됨

### ISSUE THREAD

**Issue by HBSPS** [CMC-Hackathon-Team1/Server-V2#48]
## :loudspeaker: 이슈 내용
> EC2에서 Nest Build 실패
## :page_with_curl: 상세 내용
- ![image](https://user-images.githubusercontent.com/96584994/214853111-bf5b996e-1884-474e-8e28-6a75265e7475.png)
## :round_pushpin: 참고 내용
- https://ajh322.tistory.com/242

**Comment by iamjooon2** [comment]
레퍼런스 보고 일단 살려놨습니다!
에러 내용 그대로 노드가 쓸 수 있는 메모리 사이즈가 제한이 있었던 걸로 추정됩니다! 
일단 급한 불은 끈 셈이니 이슈는 닫아둘게용
