### ISSUE TITLE
FeedCategoryMappingTable의 필요성 검토

### ISSUE THREAD

**Issue by J-MU** [CMC-Hackathon-Team1/Server-V2#64]
## :loudspeaker: 이슈 내용
> feedCategoryMapping Table존재 이유 검토와 이를 삭제했을 때 영향받는 API 검토
## :page_with_curl: 상세 내용
- feed와 category사이의 연관을 나타내기 위해 현재 feedCategoryMappingTable가 존재한다. 최초 설계할 때, 어떠한 이유에서 저런 테이블이 나왔는지 모르겠으나 feed테이블에 categoryId foriegn key만으로 카테고리와의 연관 관계를 표현할 수 있다.

## :heavy_check_mark: 체크리스트
- [ ] feed는 카테고리 하나만 가질 수 있어 보인다. 이것이 맞는지 검토
- [ ] feedCategoryTable이 존재해야 구현할 수 있는 기능이 있는지 검토
- [ ] feedCategoryTable이 사라지고 포링키로 대체되었을 때 영향받는 API검토
## :round_pushpin: 참고 내용
- ERD문서

##  :question: **요청사항**
- **각자의 기능에서 FeedCategoryMapping Table이 필요하거나 혹은 사라졌을때 수정되어야 하는 API가 무엇이 있는지 댓글바람.**

**Comment by bjho606** [comment]
제 생각에도 feedCategoryMapping 테이블은 필요 없을 것 같습니다. 말씀하신대로만 처리해도 충분할 것 같습니다.

**Comment by HBSPS** [comment]
제 작업 부분은 Feed나 Category와 관련 없어서 상관없습니다

**Comment by J-MU** [comment]
수정마치고 issue close하겠습니다.
