### ISSUE TITLE
둘러보기 시간표시 기능 검토 필요

### ISSUE THREAD

**Issue by J-MU** [CMC-Hackathon-Team1/Server-V2#71]
## :loudspeaker: 이슈 내용
> 둘러보기 시간표시 기능 기획이 확정됨에 따라 둘러보기 API를 수정하였으며 이에대한 검토 요청
## :page_with_curl: 상세 내용
- 참고내용 확인 부탁
## :round_pushpin: 참고 내용
https://www.notion.so/96b54bb31dee49368d531bc06a8abeb1

**Comment by J-MU** [comment]
기능 구현 하였고 아마 팔로잉 탐색기능에서도 그대로 사용하시면 될것으로 예상되어 링크 첨부드립니다.
이보다 더 나은 방식으로 구현하신다면 피드백 부탁드리고 사용함수에서 이해가 안되는 부분이 있다면 댓글 부탁드립니다.

**Comment by bjho606** [comment]
@J-MU 확인했습니다!
이대로 진행해도 문제는 없는데 그냥 궁금한 점이, 
시간 단위 처리하는걸 지금 방식처럼 백엔드에서 다 처리해서 보내주는게 좋은지,
아니면 프론트에게는 정보 그대로 보내주고 프론트에서 원하는대로 처리하게 넘겨주는게 좋은지 잘 모르겠네요?
혹시 어느게 더 좋은 방식이신지 아시나용?

**Comment by J-MU** [comment]
@bjho606
제가 그부분은 고려를 안하고 구현했네요. 좋은 지적 감사드립니다.
저도 고민을 한번 해보고 정리해서 올리겠습니다

**Comment by bjho606** [comment]
이 부분 그냥 프론트분들이랑 정하기 나름인것 같습니다.
이왕 만드신거 이대로 사용해도 괜찮을거 같아요ㅎㅎ

**Comment by bjho606** [comment]
@J-MU 
디스코드에서 좋은 의견이 나와서 공유합니다!
```
대한민국은 모든 지역에서 같은 시간대를 쓰기 때문에 문제가 발생하지않지만,
외국의 경우 기본적인 국내 서비스를 제공하기 위해서도 다양한 시간대를 고려해야합니다.
그러한 관점에서 목표하시는 프로젝트의 범위나 타겟을 고려했을 때 국내로 한정된 서비스라면 크게 상관 없을 것 같고,
글로벌 서비스까지 고려된다면 프론트엔드에서 상황 및 지역에 맞는 시간을 처리하는 게 효율적인 것 같습니다😊
```

**Comment by J-MU** [comment]
공유 감사합니다!!
저런 시각으로는 생각을 못해봤네요!
저희 서비스는 글로벌 서비스를 바라보고 있지는 않으니 우선 구현한 부분은 유지하도록 하겠습니다.!
