### ISSUE TITLE
Query String vs Path Variable & 구조 개선

### ISSUE THREAD

**Issue by bjho606** [CMC-Hackathon-Team1/Server-V2#75]
## :loudspeaker: 이슈 내용
> URL 을 설계할 때, 언제 QS를 사용하고 언제 PV를 사용하는지에 대해서
## :page_with_curl: 상세 내용
@J-MU 님, Feed 도메인쪽을 개발하려고 살펴보다가 생각한 건데,
- 레퍼런스를 보시면, `일반적으로 우리가 어떤 자원(데이터)의 위치를 특정해서 보여줘야 할 경우 Path variable을 쓰고, 정렬하거나 필터해서 보여줘야 할 경우에 Query parameter를 쓴다` 고 하네요.
1. profileId를 전부 query string으로 받아오신걸로 보이는데, profileId는 path variable로, 나머지 (page나 category나 날짜 등) 은 query string으로 처리하는게 바람직해 보입니다.
   - ex) feeds/feedlist/{profileId} 또는 feeds/{profileId}/feedlist (어느게 더 좋은지는 잘 모르겠네요..ㅎㅎ)
2. 둘러보기 API (no.2.1.1)에서 현재 categoryId를 클라이언트가 입력하게 되어있는데, 카테고리 이름 자체를 query string 으로 받고, 그 이름으로 서버에서 catergoryId를 찾아서 검색 결과를 한꺼번에 반환하는 방식이 낫지 않을까 생각합니다.
   - 기존처럼 하면 이 API를 사용할 때마다 API를 2번씩 호출(categoryId 찾기, 게시글 찾기)하게 되는데, 효율이 더 안 좋을 거 같습니다.
   - 즉, 클라이언트가 Category API를 직접 요청하는게 아니라, 둘러보기 API를 한번 요청하면, 서버 내에서 category API를 알아서 거칠 수 있도록 하는 방식입니다.
## :heavy_check_mark: 체크리스트
- [ ] profileId 를 기존 query string 에서 path variable 로 변경
- [ ] 카테고리를 서버 안에서 처리
## :round_pushpin: 참고 내용
https://velog.io/@jcinsh/Query-string-path-variable

**Comment by bjho606** [comment]
혹시 어떻게 생각하시는지 의견 남겨주세요~

**Comment by J-MU** [comment]
우선 마감기한이 다가오고있어 수정사항을 반영할 수 있을지 클라이언트와 이야기해봐야할거같습니다.

# 1번 queryString vs PathVariable
1번의 경우 말씀하신대로 path variable이 옳은 방법으로 보입니다. 이 내용은 변경되더라도 클라이언트에서 대응 해야하는 수정사항이 많지 않을것이라 예상되므로 클라이언트와 논의해 보겠습니다.

# 2번 queryString을 통해 categoryName을 전달하는 방법

## 제비님 방식 장단점
장점: 말씀하신 방법대로 구현했을 때 성능이 향상될 것임에는 동의합니다. 네트워크 통신이 두 번 씩 이루어질 것을 한번으로 줄일 수 있기 때문입니다.

단점: 단점으로는 기획적인 이유로 카테고리 종류에 변화가 생겼을 때 확장시키기 힘들다는 단점이 있을거라 생각합니다. 그 이유는 제 방식의 장점에서 설명하겠습니다.

## 제 방식의 장단점
장점: 제비님이 말씀하신 대로 구현한다면 클라이언트에서는 정적인 카테고리 리스트를 가지고있어야합니다.
(전체 ,자기개발 , 독서 .. 등으로 유효한 카테고리 이름 리스트를 가지고 있어야 합니다.)
이렇게 될 경우 기획적으로 어떤 이용자 층이 많은지에 따라 카테고리를 추가 하고 싶을 때 유저가 어플을 업데이트하여 새로운 카테고리 리스트를 받아 와야 합니다. 카테고리 이름이 수정되거나 삭제가 되어야 한다면 수정되거나 삭제된 카테고리이름을 서버에 전송하지 않도록 업데이트를 강제 해야 합니다. 이러한 면에서 볼 때 성능 적인 부분은 다소 포기하더라도 서버에서 카테고리 리스트를 전송해주는 편이 서비스 확장면에서 유리할거라 생각해 저런 형태로 구현하였습니다. 
단점: 말씀하신 대로 성능적인 면에서 앞선 방식보다 훨씬 더 느릴 것으로 예상됩니다.

※ 클라이언트 서비스에 업데이트가 필요할 것이라는 것은 제 생각입니다. 프론트적인 지식이 부족해서 틀린 정보일 수도 있을거같습니다. 클라이언트 분이 보시고 잘못된 생각이라면 말씀해주세요!

# 대안
제비님의 방법을 듣고나서 드는 생각은
1. 최초 로그인시 GET Category API를 통해 카테고리 정보를 받아온다.
2. 클라이언트의 db나 혹은 다른 저장방식을 통해 카테고리 정보를 영구저장시킨다.
3. categoryId가 필요한 API들을 저장된 정보를 통해 호출한다.
4. 서버에서 만약 잘못된 category id를 통해 정보를 받았을 경우 정해진 statuscode:9999(예시)를 발생시킨다.
5. 클라이언트에서 위 status code가 발생하면 GET Category API를 재호출해서 Category를 업데이트 한뒤 필요한 API를 재호출한다.

위와 같은 방식을 사용한다면 평소 Feed API를 사용할 때는 한번의 호출로 Feed 정보를 받아올 수 있으며 카테고리 정보가 기획적인 이유로 수정된다고 해도 유동적으로 대처할 수 있을거라 보입니다.
제비님 생각을 먼저 여쭙고 클라이언트분들에게 위 issue공유하겠습니다.+ 블루님도 의견 말씀해주세요

**Comment by HBSPS** [comment]
categoryId를 사용하는 API가 많다면 대안이 좋은 방법일 수 있다고 생각합니다. 해당 방법을 사용하면 적은 업데이트로 변경점을 쉽게 적용할 수 있다고 생각합니다.

**Comment by bjho606** [comment]
제 생각에 **기획적인 부분**에서 먼저 결정이 필요할거 같네요.
1. 현재는 카테고리가 4개로 고정되어있는데, 앞으로 카테고리의 확장 있을 것인가?
   - 만약 없다면, 제가 말씀드린 방식이 좋을 듯 합니다.
3. 카테고리 확장을 한다면, 그 확장은 사용자가 임의로 정할 수 있는 것인가 vs 서비스 측면에서 고정적으로 정할 것인가?
2-1. 사용자가 임의로 정할 수 있다면, 이안님 현재 방식이 더 좋을 듯 합니다.
2-2. 서비스 내에서 확정적으로 추가하는 방식이라면, 이안님 대안이 더 좋은 방법일 것 같습니다.

**Comment by bjho606** [comment]
[2023.02.07] 결론
기능 개발에 더 중점을 두는 것으로 하여, 현재 방식 (2-1번) 고수하기록 결정.
추후 리팩토링을 할 수 있음.
