### ISSUE TITLE
빌드 과정에서 src/_secret에 있는 파일이 함께 빌드되지 않음

### ISSUE THREAD

**Issue by HBSPS** [CMC-Hackathon-Team1/Server-V2#80]
## :loudspeaker: 이슈 내용
> nest build시 `src/_secret` 디렉토리의 파일들이 빌드되지 않음
## :page_with_curl: 상세 내용
- nest build시 `src/_secret` 디렉토리의 파일들이 빌드되지 않음
## :heavy_check_mark: 체크리스트
- [x] `src/_secret`의 파일들도 함께 빌드되도록 수정
## :round_pushpin: 임시 방편
- CICD가 되지 않고 있으므로 직접 EC2에서 빌드 및 파일을 작성해야 함
```
cd ~/Server-V2
pm2 kill
git pull origin dev
npm i --force
npm run build (dist 폴더가 생성됨)
cd dist/src
mkdir _secret
vim firebase-admin.json
(vim 편집기를 이용해 노션에 있는 firebase-admin.json 붙여넣기)
pm2 start npm -- run node:start:dev

```

**Comment by bjho606** [comment]
혹시 gitignore에 _secret 추가해서 그런거 아닐까요..?
_secret 안에는 노출되면 안되서 아마 변경되거나 추가되면 수동으로 넣어줘야할텐데요
아 빌드랑은 상관없으려나

**Comment by HBSPS** [comment]
> 혹시 gitignore에 _secret 추가해서 그런거 아닐까요..? _secret 안에는 노출되면 안되서 아마 변경되거나 추가되면 수동으로 넣어줘야할텐데요 아 빌드랑은 상관없으려나

`/src/_secret`디렉토리에 해당 파일 수동으로 넣어놨는데 빌드하면 `dist`에는 없네요,,😢

**Comment by HBSPS** [comment]
환경 변수로 분리하여 해결했습니다! `.env`에 변경사항이 있으니 노션을 참고해주세요
