### ISSUE TITLE
해시태그 생성 (게시글 생성 중)

### ISSUE THREAD

**Issue by bjho606** [CMC-Hackathon-Team1/Server-V2#92]
## :loudspeaker: 이슈 내용
> 해시태그 값들을 HashTags 테이블을 넣을 때 single string value 여야 하지 않나..
## :page_with_curl: 상세 내용
- 게시글 생성 API 에서, 해시태그를 해시태그 테이블에 새로 넣을 때, **하나의 string 값**으로 통일시켜야할 듯 합니다. (현재는 해시태그 테이블에 들어있는 값 형태가 뒤죽박죽 섞여있음)
   - 띄어쓰기 불가 (해시태그 입력값 자체가 띄어쓰기가 불가능합니다.)
   - '#' 제거
   - 배열 X
   - 영어는 lowercase로 통일(?) - 이건 잘 모르겠네요
- 해시태그를 검색할 때, 하나의 string값이 아니면, 해시태그 테이블에서 해당 해시태그를 찾아내기가 너무 비효율적..
## :heavy_check_mark: 체크리스트
- [ ] Hashtags 테이블 데이터 튜닝
- [x] 새 해시태그를 Hashtags 테이블에 삽입할 때, 하나의 string 값으로 넣는 것으로 리팩토링
## :round_pushpin: 참고 내용

**Comment by bjho606** [comment]
@J-MU 이 부분 리팩토링 부탁드립니다..!

**Comment by J-MU** [comment]
해시태그 테이블에 들어있는 값이 하나의 string이라는 표현이 어떤 뜻인지 잘 이해가 안갑니다.

![image](https://user-images.githubusercontent.com/46997074/220584682-121609c6-4d7a-4ec0-8180-c81fe6e366cc.png)

위 테이블 내용은 제가 개발할때 테스트한 케이스들이며 하나의 단어씩 값이 들어가있는것을 확인할 수 있습니다.
![image](https://user-images.githubusercontent.com/46997074/220584833-3d350f31-fd64-4e28-b3a2-80be956ed8bb.png)
위 내용은 제가 개발하다 실수한 부분으로 현재는 저렇게 들어가지 않도록 수정되어있습니다.
![image](https://user-images.githubusercontent.com/46997074/220584949-41ec5c55-5da7-4bef-bff8-ff7f65474be3.png)
위 배열형태의 경우는 클라이언트측에서 테스트할 때의 결과값으로 보이며 의도하지 않은 형태로 저장되어있습니다.
어떻게 요청하셨는지 확인하고 버그를 찾아야할듯합니다.

1. 하나의 string형태로 넣는다는 것이 첫 번째 케이스, 즉 한 단어씩 저장하는 것으로 통일하자는 뜻이 맞을까요? 맞다면 클라이언트측과 논의하고 버그찾아 해결하겠습니다.

2. 형태 통일 부분이 필요하다는 점 인지했습니다. 다만, 영어는 lowerCase로 통일 하는 경우는 부정적으로 봅니다.
 영어를 lowerCase로 통일한다면 유저가 작성한 해시태그와 다른 형태로 값이 저장되고 노출됩니다. 만약 검색할 때 lower case인경우 upper case인 경우가 따로따로 검색된다는 점 때문에 걱정하시는 거라면 검색을 할때 LOWER()함수를 사용해서 가져온다면 대/소문자만 다른 해시태그의 경우 함께 검색이 가능해서 문제가 되지 않습니다.

**Comment by bjho606** [comment]
> 

1. 아하 버그였군요ㅎㅎ 하나의 string 형태라는게 위 사진 첫번째 케이스 처럼 되어야 한다고 한 뜻이 맞습니다!
그리고 db에 1~27번 값들 중에서 띄어쓰기까지 같이 들어간 값들이 있었는데 이건 제가 튜닝을 미리 했고, 앞으로는 띄어쓰기도 허용되면 안 될듯 합니다..! (클라이언트 분들에게도 알려드려야겠네요)
해시태그가 원래 띄어쓰기 허용이 안되기도 하지만, 해시태그 검색 부분에 query string으로 검색할 해시태그를 받을 건데, 추후에 여러 검색어를 입력받을 때 그 구분을 띄어쓰기로 받아야해서 특히 그렇습니다.
ex) ip/feeds/search?page=1&...query=검색어1 검색어2

2. 이건 저도 어떻게 하는게 좋은지 잘 몰라서 의견 여쭤본 것입니다. 이 부분은 편하신대로 해도 좋을 것 같습니다ㅎㅎ

**Comment by J-MU** [comment]
1번에서 여러 검색어를 받을 때 띄어쓰기로 받아야한다는 점이 의문입니다.
혹시나 다른 방법이 떠오르지 않아서 그러신거라면 queryString은 같은 값으로 요청을 줄 수 있습니다.

예를 들어,
ip/feeds/search?page=1&hashTag=하하하&hashTag=호호호&hashTag=히히히 로 요청을 준다면 서버에서는
hashTag=["하하하","호호호","히히히"] 형태로 전달됩니다.

예시를 위해 간단한 함수를 하나 작성하였습니다.
![image](https://user-images.githubusercontent.com/46997074/220592050-4771ac71-8bf2-442b-9412-7d574ac1f4b0.png)

이를 아래와 같이 포스트맨에서 전송해보면
![image](https://user-images.githubusercontent.com/46997074/220592160-e8c4cf55-8cbc-42e0-b9a8-af333784aadf.png)

["호","히"]와 같이 배열에 담겨 리턴 되는 것을 확인할 수 있습니다.
아래는 vscode terminal에 hashTagList를 console.log()찍어본 결과입니다.
![image](https://user-images.githubusercontent.com/46997074/220592371-5c3cdcc5-8475-4f79-82a3-98a8a4979152.png)

띄어쓰기로 hashTag를 구분하는 것 보다 이 방법이 훨씬 나은 방법으로 보여 의견 남깁니다.

**Comment by J-MU** [comment]
아 물론 띄어쓰기는 못하게 만들겠습니다

**Comment by bjho606** [comment]
> 1번에서 여러 검색어를 받을 때 띄어쓰기로 받아야한다는 점이 의문입니다. 혹시나 다른 방법이 떠오르지 않아서 그러신거라면 queryString은 같은 값으로 요청을 줄 수 있습니다.
> 
> 예를 들어, ip/feeds/search?page=1&hashTag=하하하&hashTag=호호호&hashTag=히히히 로 요청을 준다면 서버에서는 hashTag=["하하하","호호호","히히히"] 형태로 전달됩니다.
> 
> 예시를 위해 간단한 함수를 하나 작성하였습니다. ![image](https://user-images.githubusercontent.com/46997074/220592050-4771ac71-8bf2-442b-9412-7d574ac1f4b0.png)
> 
> 이를 아래와 같이 포스트맨에서 전송해보면 ![image](https://user-images.githubusercontent.com/46997074/220592160-e8c4cf55-8cbc-42e0-b9a8-af333784aadf.png)
> 
> ["호","히"]와 같이 배열에 담겨 리턴 되는 것을 확인할 수 있습니다. 아래는 vscode terminal에 hashTagList를 console.log()찍어본 결과입니다. ![image](https://user-images.githubusercontent.com/46997074/220592371-5c3cdcc5-8475-4f79-82a3-98a8a4979152.png)
> 
> 띄어쓰기로 hashTag를 구분하는 것 보다 이 방법이 훨씬 나은 방법으로 보여 의견 남깁니다.

홀리몰리 이게 되는지는 몰랐네요..! 검색어 여러개 얘기는 띄어쓰기 허용하면 안되는 이유를 하나 더 찾다보니까 생각난거여서 별개로 생각해도 됩니당ㅎㅎ 알려주셔서 감사합니다!
